# -*- coding: utf-8 -*-
# Generated by Django 1.11.27 on 2020-03-30 09:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hueylogs', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='hueyexecutionlog',
            name='error_description',
            field=models.TextField(blank=True),
        ),
    ]
