# -*- coding: utf-8 -*-
# Generated by Django 1.11.27 on 2020-12-04 16:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hueylogs', '0002_hueyexecutionlog_error_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='hueyexecutionlog',
            name='finnished',
            field=models.NullBooleanField(default=None),
        ),
    ]
