# Generated by Django 3.2.4 on 2021-06-11 09:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hueylogs', '0003_hueyexecutionlog_finnished'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hueyexecutionlog',
            name='finnished',
            field=models.BooleanField(default=None, null=True),
        ),
    ]
